language: c

env:
  global:
    # Ubuntu version
    - LINUX_DIST=trusty
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
compiler:
  - gcc
  - clang
os:
  - linux
branches:
  only:
    - master

before_install:
  - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
  - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

install:
    - CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v3.16.1/cmake-3.16.1.tar.gz"
    - mkdir -p ${DEPS_DIR}/cmake
    - travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
    - export PATH=${DEPS_DIR}/cmake/bin:${PATH}

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make